name: "ZAP Baseline Scan"

on:
  push:
    branches:
      - master

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
          ref: master
       - name: Pulling Docker Image
         run: docker pull bkimminich/juice-shop
       - name: Launching the app
         run: docker run --rm -d -p 3000:3000 bkimminich/juice-shop
    
       - name: OWASP ZAP
         uses: zaproxy/action-baseline@v0.7.0
         with:
           # Target URL
           target: "http://localhost:3000"
           rules_file_name: ".zap/rules.tsv"
           fail_action: false
           command_opts: "-x .zap/work/zap-report.xml"

       - name: Upload ZAP report
         run: |
          curl -X POST -H "api-token: <your-api-token>" -F "fileName=@.zap/work/zap-report.xml" "demo.iriusrisk.com/api/v1/products/<ref>/tests/zap/upload"
