name: "ZAP Baseline Scan"

on:
  push:
    branches:
      - master

jobs:
  pull:
    runs-on: ubuntu-latest
    outputs:
      runner: ${{ steps.docker-runner.outputs.runner }}
    steps:
      - uses: actions/checkout@v2
      - name: juice-shop
        run: docker pull bkimminich/juice-shop
      - name: get docker runner
        id: docker-runner
        run: echo "::set-output name=runner::$(docker run -d -p 3000:3000 bkimminich/juice-shop)"

  zap_scan:
    needs: pull
    runs-on: ${{ needs.pull.outputs.runner }}
    name: Scan docker image with ZAP
    steps:
      - name: Pull docker image of ZAP
        run: docker pull owasp/zap2docker-stable
      - name: Run ZAP scan
        run: docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:3000/
