name: "ZAP Baseline Scan"

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop with ZAP
    steps:
      - uses: actions/checkout@v2

      - name: Start Juice Shop
        run: npm install && npm start --prefix ./juice-shop &

      - name: Wait for Juice Shop to start
        run: sleep 30

      - name: Run ZAP scan
        run: |
          sudo apt-get update
          sudo apt-get install -y zaproxy
          zap-cli --version
          zap-cli start --daemon -config api.disablekey=true
          zap-cli --verbose --output /zap/wrk/zap-baseline-report.html \
            baseline-scan \
            --baseline /zap/wrk/baseline.conf \
            --output-format html \
            --spider \
            --start "http://localhost:3000/" \
            --context-name "Juice Shop"
          zap-cli alerts --base "http://localhost:3000/" --exit-code False

      - name: Stop Juice Shop
        run: kill $(ps aux | grep '[n]pm start' | awk '{print $2}')
