name: "ZAP Baseline Scan"

on:
  push:
    branches:
      - master
#  schedule:
#    - cron:  '0 18 * * 6'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull Juice Shop image
        run: docker pull bkimminich/juice-shop
      - name: Run Juice Shop container
        run: docker run --rm -p 3000:3000 bkimminich/juice-shop
        timeout-minutes: 10
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14.x'
#       - name: Install dependencies
#         run: npm install
#       - name: Build application
#         run: npm run build
#       - name: Serve application
#         run: npm start

  zap_scan:
    needs: build
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: Check out Git repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f #v2: v2.3.4 available
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'
