name: "ZAP Baseline Scan"

on:
  push:
    branches:
      - master

jobs:
  test:
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
         with:
          ref: master
       - name: Pulling Docker Image
         run: docker pull bkimminich/juice-shop
       - name: Launching the app
         run: docker run --rm -d -p 3000:3000 bkimminich/juice-shop
    
       - name: OWASP ZAP
         uses: zaproxy/action-baseline@v0.4.0
         with:
           # Target URL
           target: "http://localhost:3000"
           fail_action: false
           token: $
           issue_title: Security Tests
